"""Step 5.8 — assemble the code-ready use-case specification (addendum D-43, D-49).

The specification follows the company SRS skeleton first — the use case description table, the activities
flow and the step-keyed Business Rules table — then the kit's technical sections. Every section but two is
copied or derived *by the tool* from the upstream artifacts and catalogs: a model re-typing six documents
into one invites paraphrase drift and costs tokens. The spec agent writes only the narrative sections
(NARRATIVE). Re-running `tools/ba compile <UC>` refreshes the generated sections and keeps the narrative
ones. `tools/ba validate` rejects hand edits to generated sections and narrative sections left empty.
"""
from __future__ import annotations

import re
from typing import Dict, List, Optional, Tuple

from . import paths, schema, store
from .ids import MESSAGE_PREFIXES, as_list, find_refs, normalize_id, prefix_of
from .store import BAError
from .workspace import Doc, Workspace, field, sections, subsection

NARRATIVE = {11: "why the use case matters: the process step (BP-…-S…), the requirements it satisfies and "
                 "the business outcome",
             15: "other use cases, integrations and open technical decisions it depends on"}
PLACEHOLDER = "<!-- TODO(spec-agent): {hint} -->"
PLACEHOLDER_RE = re.compile(r"<!-- TODO\(spec-agent\):")
MARK = "<!-- generated by `tools/ba compile` from {src} — change the source, then re-run it -->"
MARK_RE = re.compile(r"^<!-- generated by `tools/ba compile`.*-->\s*$", re.M)
REQUIRED_UPSTREAM = ("use-case-behaviour", "sequence", "api-design", "acceptance-criteria")
UI_UPSTREAM = ("ui-markdown", "ui-prototype")
SECTION_RE = re.compile(r"^(\d+)\.\s")
FIELD_LINE_RE = re.compile(r"^\s*-\s*\*\*(Step|Type|State change):?\*\*")
ACCESS_SYMBOL = {"ALL": "O", "OWN": "O*", "SCOPED": "O**", "NONE": "X"}


def headings() -> List[str]:
    return schema.artifact_type("use-case-specification")["headings"]


def upstream(ws: Workspace, uc: str) -> Dict[str, Doc]:
    out, missing, stale = {}, [], []
    types = REQUIRED_UPSTREAM + (UI_UPSTREAM if ws.ui_required(uc) else ())
    for t in types:
        rel = ws.doc_rel(t, uc)
        doc = ws.docs.get(rel)
        if doc is None:
            missing.append(paths.show(rel))
            continue
        if ws.stale_reasons(doc):
            stale.append(paths.show(rel))
        out[t] = doc
    if missing:
        raise BAError("cannot compile: missing " + ", ".join(missing))
    if stale:
        raise BAError("cannot compile: regenerate the stale inputs first: " + ", ".join(stale))
    return out


def _section(doc: Doc, title: str) -> Optional[str]:
    t = title.lower()
    for _lvl, h, text in sections(doc.body):
        if re.sub(r"^\d+\.\s*", "", h).strip().lower() == t:
            return text.strip()
    return None


def _scoped(ws: Workspace, doc: Doc, kind: str) -> str:
    items = sorted((sid, x) for sid, x in ws.scoped.items() if x["doc"] == doc.rel and x["kind"] == kind)
    if not items:
        return "None."
    return "\n\n".join(f"### {sid} — {x['title']}\n{x['text'].strip()}" for sid, x in items)


def _cell(text: str) -> str:
    """Markdown → one table cell: line breaks as <br>, bullets as •, pipes escaped."""
    lines = []
    for ln in text.strip().split("\n"):
        s = ln.rstrip()
        if not s.strip():
            continue
        m = re.match(r"^(\s*)[-*]\s+(.*)$", s)
        if m:
            s = ("&nbsp;&nbsp;" * (len(m.group(1)) // 2)) + "• " + m.group(2)
        lines.append(s.strip() if not m else s)
    return "<br>".join(lines).replace("|", "\\|")


def field_block(text: str, name: str) -> Optional[str]:
    """A '- **Name:** value' field with the indented lines that continue it."""
    lines = text.split("\n")
    for i, ln in enumerate(lines):
        m = re.match(r"^\s*-\s*\*\*" + re.escape(name) + r":?\*\*:?[ \t]*(.*)$", ln, re.I)
        if not m:
            continue
        out = [m.group(1).strip()] if m.group(1).strip() else []
        for nxt in lines[i + 1:]:
            if re.match(r"^\s*-\s*\*\*[^*]+\*\*", nxt) or (nxt.strip() and not nxt.startswith((" ", "\t"))):
                break
            if nxt.strip():
                out.append(nxt.strip())
        return "\n".join(out)
    return None


def _union(docs, key: str) -> List[str]:
    out: List[str] = []
    for d in docs:
        vals = (d.fm.get("relations") or {}).get(key) if key not in ("open_questions", "assumptions") \
            else d.fm.get(key)
        out += [v for v in as_list(vals) if v not in out]
    return out


def relations(ws: Workspace, uc: str, ups: Dict[str, Doc]) -> Dict[str, List[str]]:
    item = ws.item(uc) or {}
    docs = list(ups.values())
    rel = {"business_process": as_list(item.get("business_process")),
           "requirements": as_list(item.get("requirements")),
           "common_use_cases": as_list(item.get("follows"))}
    for key in ("business_rules", "entities_read", "entities_written", "screens", "apis", "integrations",
                "messages", "email_templates"):
        vals = as_list(item.get(key)) if key in ("business_rules", "entities_read", "entities_written") else []
        rel[key] = vals + [v for v in _union(docs, key) if v not in vals]
    if item.get("object") and item["object"] not in rel["entities_read"] + rel["entities_written"]:
        rel["entities_read"] = [item["object"]] + rel["entities_read"]
    return {k: v for k, v in rel.items() if v}


def step_rules(ws: Workspace, doc: Doc) -> List[Tuple[str, dict]]:
    return sorted((sid, x) for sid, x in ws.scoped.items() if x["doc"] == doc.rel and x["kind"] == "BR")


def rule_description(text: str) -> str:
    """A step rule's description: its text without the **Step:** / **Type:** / **State change:** lines."""
    return "\n".join(ln for ln in text.strip().split("\n") if not FIELD_LINE_RE.match(ln)).strip()


def business_rules_table(ws: Workspace, uc: str, beh: Doc) -> str:
    """The company's step-keyed Business Rules table: followed CMUC rules first, then the use case's own."""
    rows = ["| Step | BR Code | Description |", "|---|---|---|"]
    for c in as_list((ws.item(uc) or {}).get("follows")):
        for r in as_list((ws.item(c) or {}).get("step_rules")):
            if isinstance(r, dict):
                rows.append(f"| {c} {r.get('step', '')} | {r.get('id', '')} | "
                            f"{_cell('**' + str(r.get('title', '')) + ':**' + chr(10) + str(r.get('description', '')))} |")
    for sid, x in step_rules(ws, beh):
        step = field(x["text"], "Step") or ""
        rows.append(f"| {step} | {sid} | {_cell('**' + x['title'] + ':**' + chr(10) + rule_description(x['text']))} |")
    return "\n".join(rows) if len(rows) > 2 else "None."


def message_rows(ws: Workspace, codes: List[str]) -> str:
    rows = ["| Code | Type | Message |", "|---|---|---|"]
    for c in codes:
        m = ws.item(c) or {}
        rows.append(f"| {c} | {str(m.get('type', '')).replace('_', ' ').title()} | {_cell(str(m.get('text', '')))} |")
    return "\n".join(rows) if len(rows) > 2 else "None."


def email_template_block(ws: Workspace, et: str) -> str:
    e = ws.item(et) or {}
    out = [f"### {et} — {e.get('name', '')}", "", f"| Send to | {_cell(str(e.get('to', '')))} |", "|---|---|"]
    if e.get("cc"):
        out.append(f"| CC | {_cell(str(e['cc']))} |")
    out += [f"| Subject | {_cell(str(e.get('subject', '')))} |", f"| Body | {_cell(str(e.get('body', '')))} |", "",
            f"Sent when: {e.get('trigger', '')}", ""]
    ph = [p for p in as_list(e.get("placeholders")) if isinstance(p, dict)]
    if ph:
        out += ["Placeholders:", ""] + [f"- <<{p.get('name')}>>: {p.get('source')}" for p in ph]
    return "\n".join(out).rstrip()


def _used_codes(ws: Workspace, uc: str, docs: List[Doc], prefixes) -> List[str]:
    text = "\n".join(d.body for d in docs)
    for c in as_list((ws.item(uc) or {}).get("follows")):
        text += "\n" + " ".join(str(r.get("description", "")) for r in as_list((ws.item(c) or {}).get("step_rules"))
                                if isinstance(r, dict))
    return sorted(r for r in find_refs(text) if prefix_of(r) in prefixes and ws.item(r) is not None)


def generated(ws: Workspace, uc: str, ups: Dict[str, Doc]) -> Dict[int, Tuple[str, str]]:
    """section number → (source description, content)."""
    item = ws.item(uc) or {}
    rel = relations(ws, uc, ups)
    beh, seq, api, acc = (ups["use-case-behaviour"], ups["sequence"], ups["api-design"], ups["acceptance-criteria"])
    ui = ups.get("ui-markdown")
    uc_cat = schema.catalogs()["use-cases"]["path"]
    out: Dict[int, Tuple[str, str]] = {}

    actors = [a for a in as_list(item.get("actor"))]
    names = ", ".join(str((ws.item(a) or {}).get("name", a)) for a in actors)
    head = field_block(subsection(beh.body, "Use Case Description") or "", "Trigger")
    pre = field_block(subsection(beh.body, "Use Case Description") or "", "Pre-condition")
    post = field_block(subsection(beh.body, "Use Case Description") or "", "Post-condition")
    perms = "; ".join(f"{(ws.item(p.get('actor')) or {}).get('name', p.get('actor'))}: "
                      f"{ACCESS_SYMBOL.get(p.get('access'), 'X')}" + (f" ({p['scope']})" if p.get("scope") else "")
                      for p in as_list(item.get("permissions")) if isinstance(p, dict)
                      and p.get("access") not in (None, "NONE"))
    rows = [f"| Use case | {uc} — {_cell(str(item.get('name', '')))} |", "|---|---|",
            f"| Objective | This use case allows {names} to {_cell(str(item.get('objective', '')))}. |",
            f"| Actor | {names} |",
            f"| Trigger | {_cell(head or '')} |",
            f"| Pre-condition | {_cell(pre or '')} |",
            f"| Post-condition | {_cell(post or '')} |"]
    if item.get("follows"):
        rows.append("| Follows | " + ", ".join(f"{c} {ws.label(c)}" for c in as_list(item.get("follows")))
                    + " — the sections below state only what differs |")
    if perms:
        rows.append(f"| Permission | {perms} |")
    out[1] = (f"{uc_cat}, {paths.show(beh.rel)}", "\n".join(rows))

    flows = []
    for c in as_list(item.get("follows")):
        cm = ws.item(c) or {}
        flows += [f"#### {c} — {cm.get('name', '')} (common use case)", ""]
        flows += [f"- {s}" for s in as_list(cm.get("activities_flow"))] + [""]
    own = (subsection(beh.body, "Activities Flow") or "").strip()
    if flows:
        flows += [f"#### Specific to {uc}", ""]
    out[2] = (paths.show(beh.rel), "\n".join(flows + [own or "None."]).strip())

    out[3] = (paths.show(beh.rel) + (", " + schema.catalogs()["common-use-cases"]["path"] if item.get("follows") else ""),
              business_rules_table(ws, uc, beh))
    out[4] = (paths.show(beh.rel), _scoped(ws, beh, "AF"))
    out[5] = (paths.show(beh.rel), _scoped(ws, beh, "EF"))

    br_ids = [b for b in rel.get("business_rules", [])]
    br_ids += [b for b in _used_codes(ws, uc, list(ups.values()), ("BR",)) if b not in br_ids]
    rules = []
    for br in br_ids:
        b = ws.item(br) or {}
        kind = "Common" if b.get("kind") == "COMMON" else "Policy"
        rules.append(f"- **{br} — {b.get('name', '')}** ({kind}): {b.get('description', '')}")
    out[6] = (schema.catalogs()["business-rules"]["path"], "\n".join(rules) or "None.")

    if ui is not None:
        scr = [(h, t) for _l, h, t in sections(ui.body) if re.match(r"^SCR-\d{3,4}\b", h)]
        proto = paths.show(ws.input_rel("ui-prototype", uc))
        text = "\n\n".join(f"### {h}\n{t.strip()}" for h, t in scr) or "None."
        out[7] = (f"{paths.show(ui.rel)}, {proto}", f"Interactive prototype: `{proto}index.html`.\n\n{text}")
    else:
        out[7] = (uc_cat, "Not applicable: a system use case with no screens (addendum D-57).")

    codes = _used_codes(ws, uc, list(ups.values()), MESSAGE_PREFIXES)
    out[8] = (schema.catalogs()["messages"]["path"], message_rows(ws, codes))
    ets = _used_codes(ws, uc, [beh], ("ET",))
    out[9] = (schema.catalogs()["email-templates"]["path"],
              "\n\n".join(email_template_block(ws, e) for e in ets) or "None.")

    rows = ["| Entity | Name | Access | Lifecycle states |", "|---|---|---|---|"]
    for e in rel.get("entities_read", []) + [x for x in rel.get("entities_written", [])
                                               if x not in rel.get("entities_read", [])]:
        ent = ws.item(e) or {}
        access = "/".join(a for a, k in (("read", "entities_read"), ("write", "entities_written"))
                          if e in rel.get(k, []))
        states = ", ".join(str(x) for x in as_list((ent.get("lifecycle") or {}).get("states"))) or "—"
        rows.append(f"| {e}{' (object)' if e == item.get('object') else ''} | {ent.get('name', '')} | {access} | {states} |")
    out[10] = (schema.catalogs()["entities"]["path"], "\n".join(rows) if len(rows) > 2 else "None.")

    main = _section(seq, "Main Flow")
    if not main or "```mermaid" not in main:
        m = re.search(r"```mermaid.*?```", seq.body, re.S)
        main = m.group(0) if m else "None."
    out[12] = (paths.show(seq.rel), main)

    summary = _section(api, "API Summary") or "None."
    out[13] = (paths.show(api.rel), f"{summary}\n\nFull request/response schemas, validation and errors: "
                                    f"`ba-ai/{api.rel}`.")

    out[14] = (paths.show(acc.rel), _scoped(ws, acc, "AC"))

    asm_ids = _union(ups.values(), "assumptions")
    asm_ids += [a["id"] for a in ws.items_in("assumptions") if uc in as_list(a.get("related"))
                and a.get("status") != "REJECTED" and a["id"] not in asm_ids]
    asms = [f"- **{a}** ({(ws.item(a) or {}).get('status', '')}): {(ws.item(a) or {}).get('statement', '')}"
            for a in asm_ids if ws.item(a)]
    out[16] = (schema.catalogs()["assumptions"]["path"], "\n".join(asms) or "None.")

    q_ids = _union(ups.values(), "open_questions")
    q_ids += [q["id"] for q in ws.items_in("open-questions") if uc in as_list(q.get("related"))
              and q.get("status") != "CLOSED" and q["id"] not in q_ids]
    qs = []
    for q in q_ids:
        it = ws.item(q) or {}
        if not it:
            continue
        line = f"- **{q}** [{it.get('status', '')}, {it.get('target_stakeholder', '')}]: {it.get('question', '')}"
        if it.get("answer"):
            line += f" — **Answer:** {it['answer']}"
        qs.append(line)
    out[17] = (schema.catalogs()["open-questions"]["path"], "\n".join(qs) or "None.")

    step = next((sid for sid, rec in ws.steps.items() if uc in as_list(rec["step"].get("use_cases"))), None)
    head_lines = [f"**Requirements:** " + (", ".join(f"{r} {ws.label(r)}" for r in rel.get("requirements", [])) or "—"),
                  f"**Process step:** " + (f"{step} {ws.label(step)}" if step else
                                           ", ".join(rel.get("business_process", [])) or "—"),
                  f"**User stories:** " + (", ".join(f"{s['id']} {s.get('name', '')}" for s in ws.items_in("user-stories")
                                                     if s.get("use_case") == uc) or "—"), ""]
    rows = ["| Acceptance criterion | Rules | Step rules and flows | Screens | APIs |", "|---|---|---|---|---|"]
    for sid, x in sorted((s, x) for s, x in ws.scoped.items() if x["doc"] == acc.rel and x["kind"] == "AC"):
        refs = find_refs(x["text"])
        brs = sorted(r for r in refs if prefix_of(r) in ("BR", "REQ") and "-BR-" not in r)
        flows_ = sorted(r for r in refs if re.search(r"-(BR|AF|EF)-\d{2}$", r))
        scr_ = sorted(r for r in refs if prefix_of(r) == "SCR") or rel.get("screens", [])
        apis = sorted(r for r in refs if prefix_of(r) == "API") or rel.get("apis", [])
        rows.append(f"| {sid} | {', '.join(brs) or '—'} | {', '.join(flows_) or '—'} | "
                    f"{', '.join(scr_) or '—'} | {', '.join(apis) or '—'} |")
    out[18] = ("the artifacts above", "\n".join(head_lines + rows))
    return out


def _existing_sections(doc: Optional[Doc]) -> Dict[int, str]:
    if doc is None:
        return {}
    out = {}
    for lvl, h, text in sections(doc.body):
        m = SECTION_RE.match(h)
        if lvl == 2 and m:
            out[int(m.group(1))] = text.strip()
    return out


def strip_mark(text: str) -> str:
    return MARK_RE.sub("", text).strip()


def compile_spec(uc_arg: str) -> dict:
    from .sync import stamp_doc
    uc = normalize_id(uc_arg)
    with store.locked():
        ws = Workspace()
        if ws.catalog_of(uc) != "use-cases":
            raise BAError(f"{uc} is not a use case")
        ups = upstream(ws, uc)
        rel = ws.doc_rel("use-case-specification", uc)
        old = ws.docs.get(rel)
        prev = _existing_sections(old)
        gen = generated(ws, uc, ups)
        body = [f"# {uc} — {ws.label(uc)}", ""]
        todo = []
        for n, h in enumerate(headings(), 1):
            body += [f"## {n}. {h}", ""]
            if n in gen:
                src, content = gen[n]
                body += [MARK.format(src=src), "", content, ""]
            else:
                text = prev.get(n, "")
                if not text or PLACEHOLDER_RE.search(text):
                    text = PLACEHOLDER.format(hint=NARRATIVE.get(n, "write this section"))
                    todo.append(f"{n}. {h}")
                body += [text, ""]
        fm = dict(old.fm) if old else {"id": uc, "artifact_type": "use-case-specification", "status": "DRAFT",
                                       "version": 1, "baseline": "TO_BE", "origin": "AI"}
        fm.update({"title": ws.label(uc), "relations": relations(ws, uc, ups),
                   "open_questions": _union(ups.values(), "open_questions"),
                   "assumptions": _union(ups.values(), "assumptions"), "updated_at": store.now()})
        p = paths.BA / rel
        store.write_frontmatter(p, fm, "\n".join(body).rstrip() + "\n")
        ws2 = Workspace()
        stamp_doc(ws2, ws2.docs[rel])
    return {"path": paths.show(rel), "narrative_todo": todo}


def check(ws: Workspace, doc: Doc) -> List[str]:
    """Validation messages: placeholders left, or generated sections edited by hand."""
    msgs = []
    have = _existing_sections(doc)
    for n, h in enumerate(headings(), 1):
        if n in NARRATIVE and PLACEHOLDER_RE.search(have.get(n, "")):
            msgs.append(f"section {n}. {h} still has the TODO placeholder — write it")
    if ws.stale_reasons(doc):
        return msgs
    try:
        ups = upstream(ws, doc.id)
    except BAError:
        return msgs
    for n, (src, content) in generated(ws, doc.id, ups).items():
        if " ".join(strip_mark(have.get(n, "")).split()) != " ".join(content.split()):
            msgs.append(f"section {n}. {headings()[n - 1]} differs from its source ({src}) — "
                        f"don't edit generated sections: change the source, then `tools/ba compile {doc.id}`")
    return msgs
