"""Step 5.8 — assemble the code-ready use-case specification (addendum D-43).

Most of the 20 sections are copied or derived *by the tool* from the upstream artifacts and catalogs:
a model re-typing six documents into one invites small paraphrase drift and costs tokens. The spec
agent writes only the narrative sections (NARRATIVE). Re-running `tools/ba compile <UC>` refreshes the
generated sections and keeps the narrative ones. `tools/ba validate` rejects hand edits to generated
sections and narrative sections left empty.
"""
from __future__ import annotations

import re
from typing import Dict, List, Optional, Tuple

from . import paths, schema, store
from .ids import as_list, find_refs, normalize_id, prefix_of
from .store import BAError
from .workspace import Doc, Workspace, sections

NARRATIVE = {1: "the goal, in business terms (use case description, requirements)",
             3: "what must be true before the actor starts (from the UI, activity analysis and rules)",
             4: "what starts the use case (process step, screen action, schedule, event)",
             5: "the process step (BP-…-S…), the requirements it satisfies and why it matters",
             6: "a short numbered user journey across the screens",
             8: "numbered system-level steps: actor action → system response (from the UI and sequence)",
             17: "other use cases, integrations and open technical decisions it depends on"}
PLACEHOLDER = "<!-- TODO(spec-agent): {hint} -->"
PLACEHOLDER_RE = re.compile(r"<!-- TODO\(spec-agent\):")
MARK = "<!-- generated by `tools/ba compile` from {src} — change the source, then re-run it -->"
MARK_RE = re.compile(r"^<!-- generated by `tools/ba compile`.*-->\s*$", re.M)
UPSTREAM = ("ui-markdown", "ui-prototype", "sequence", "api-design", "activity-validation", "acceptance-criteria")
SECTION_RE = re.compile(r"^(\d+)\.\s")


def headings() -> List[str]:
    return schema.artifact_type("use-case-specification")["headings"]


def upstream(ws: Workspace, uc: str) -> Dict[str, Doc]:
    out, missing, stale = {}, [], []
    for t in UPSTREAM:
        rel = ws.doc_rel(t, uc)
        doc = ws.docs.get(rel)
        if doc is None:
            missing.append(paths.show(rel))
            continue
        if ws.stale_reasons(doc):
            stale.append(paths.show(rel))
        out[t] = doc
    if missing:
        raise BAError("cannot compile: missing " + ", ".join(missing))
    if stale:
        raise BAError("cannot compile: regenerate the stale inputs first: " + ", ".join(stale))
    return out


def _section(doc: Doc, title: str) -> Optional[str]:
    t = title.lower()
    for _lvl, h, text in sections(doc.body):
        if re.sub(r"^\d+\.\s*", "", h).strip().lower() == t:
            return text.strip()
    return None


def _scoped(ws: Workspace, doc: Doc, kind: str) -> str:
    items = sorted((sid, x) for sid, x in ws.scoped.items() if x["doc"] == doc.rel and x["kind"] == kind)
    if not items:
        return "None."
    return "\n\n".join(f"### {sid} — {x['title']}\n{x['text'].strip()}" for sid, x in items)


def _union(docs, key: str) -> List[str]:
    out: List[str] = []
    for d in docs:
        vals = (d.fm.get("relations") or {}).get(key) if key not in ("open_questions", "assumptions") \
            else d.fm.get(key)
        out += [v for v in as_list(vals) if v not in out]
    return out


def relations(ws: Workspace, uc: str, ups: Dict[str, Doc]) -> Dict[str, List[str]]:
    item = ws.item(uc) or {}
    docs = list(ups.values())
    rel = {"business_process": as_list(item.get("business_process")),
           "requirements": as_list(item.get("requirements"))}
    for key in ("business_rules", "entities_read", "entities_written", "screens", "apis", "integrations"):
        vals = as_list(item.get(key)) if key in ("business_rules", "entities_read", "entities_written") else []
        rel[key] = vals + [v for v in _union(docs, key) if v not in vals]
    return {k: v for k, v in rel.items() if v}


def generated(ws: Workspace, uc: str, ups: Dict[str, Doc]) -> Dict[int, Tuple[str, str]]:
    """section number → (source description, content)."""
    item = ws.item(uc) or {}
    rel = relations(ws, uc, ups)
    act = ws.item(item.get("actor")) or {}
    ui, seq, api, act_doc, acc = (ups["ui-markdown"], ups["sequence"], ups["api-design"],
                                  ups["activity-validation"], ups["acceptance-criteria"])
    out: Dict[int, Tuple[str, str]] = {}

    out[2] = ("overview/actors.yaml",
              f"**{item.get('actor')} — {act.get('name', '')}** ({act.get('type', '')}). {act.get('description', '')}".strip())

    screens = [(h, t) for _l, h, t in sections(ui.body) if re.match(r"^SCR-\d{3,4}\b", h)]
    ui_text = "\n\n".join(f"### {h}\n{t.strip()}" for h, t in screens) or "None."
    out[7] = (f"{paths.show(ui.rel)}, ui/prototypes/{uc}/",
              f"Interactive prototype: `ba-ai/ui/prototypes/{uc}/index.html`.\n\n{ui_text}")

    out[9] = (paths.show(act_doc.rel), _scoped(ws, act_doc, "AF"))
    out[10] = (paths.show(act_doc.rel), _scoped(ws, act_doc, "EF"))

    rules = [f"- **{br} — {(ws.item(br) or {}).get('name', '')}:** {(ws.item(br) or {}).get('description', '')}"
             for br in rel.get("business_rules", [])]
    out[11] = ("overview/business-rules.yaml", "\n".join(rules) or "None.")

    out[12] = (paths.show(act_doc.rel), _scoped(ws, act_doc, "VR"))

    rows = ["| Entity | Name | Access | Lifecycle states |", "|---|---|---|---|"]
    for e in rel.get("entities_read", []) + [x for x in rel.get("entities_written", [])
                                               if x not in rel.get("entities_read", [])]:
        ent = ws.item(e) or {}
        access = "/".join(a for a, k in (("read", "entities_read"), ("write", "entities_written"))
                          if e in rel.get(k, []))
        states = ", ".join(str(x) for x in as_list((ent.get("lifecycle") or {}).get("states"))) or "—"
        rows.append(f"| {e} | {ent.get('name', '')} | {access} | {states} |")
    out[13] = ("overview/data-model/entities.yaml", "\n".join(rows) if len(rows) > 2 else "None.")

    main = _section(seq, "Main Flow")
    if not main or "```mermaid" not in main:
        m = re.search(r"```mermaid.*?```", seq.body, re.S)
        main = m.group(0) if m else "None."
    out[14] = (paths.show(seq.rel), main)

    summary = _section(api, "API Summary") or "None."
    out[15] = (paths.show(api.rel), f"{summary}\n\nFull request/response schemas, validation and errors: "
                                    f"`ba-ai/{api.rel}`.")

    out[16] = (paths.show(acc.rel), _scoped(ws, acc, "AC"))

    asm_ids = _union(ups.values(), "assumptions")
    asm_ids += [a["id"] for a in ws.items_in("assumptions") if uc in as_list(a.get("related"))
                and a.get("status") != "REJECTED" and a["id"] not in asm_ids]
    asms = [f"- **{a}** ({(ws.item(a) or {}).get('status', '')}): {(ws.item(a) or {}).get('statement', '')}"
            for a in asm_ids if ws.item(a)]
    out[18] = ("requirements/assumptions/assumptions.yaml", "\n".join(asms) or "None.")

    q_ids = _union(ups.values(), "open_questions")
    q_ids += [q["id"] for q in ws.items_in("open-questions") if uc in as_list(q.get("related"))
              and q.get("status") != "CLOSED" and q["id"] not in q_ids]
    qs = []
    for q in q_ids:
        it = ws.item(q) or {}
        if not it:
            continue
        line = f"- **{q}** [{it.get('status', '')}, {it.get('target_stakeholder', '')}]: {it.get('question', '')}"
        if it.get("answer"):
            line += f" — **Answer:** {it['answer']}"
        qs.append(line)
    out[19] = ("requirements/clarification-log/open-questions.yaml", "\n".join(qs) or "None.")

    step = next((sid for sid, rec in ws.steps.items() if uc in as_list(rec["step"].get("use_cases"))), None)
    head = [f"**Requirements:** " + (", ".join(f"{r} {ws.label(r)}" for r in rel.get("requirements", [])) or "—"),
            f"**Process step:** " + (f"{step} {ws.label(step)}" if step else
                                     ", ".join(rel.get("business_process", [])) or "—"), ""]
    rows = ["| Acceptance criterion | Rules | Validations and flows | Screens | APIs |", "|---|---|---|---|---|"]
    for sid, x in sorted((s, x) for s, x in ws.scoped.items() if x["doc"] == acc.rel and x["kind"] == "AC"):
        refs = find_refs(x["text"])
        brs = sorted(r for r in refs if prefix_of(r) in ("BR", "REQ"))
        flows = sorted(r for r in refs if re.search(r"-(VR|AF|EF)-\d{2}$", r))
        scr = sorted(r for r in refs if prefix_of(r) == "SCR") or rel.get("screens", [])
        apis = sorted(r for r in refs if prefix_of(r) == "API") or rel.get("apis", [])
        rows.append(f"| {sid} | {', '.join(brs) or '—'} | {', '.join(flows) or '—'} | "
                    f"{', '.join(scr) or '—'} | {', '.join(apis) or '—'} |")
    out[20] = ("the artifacts above", "\n".join(head + rows))
    return out


def _existing_sections(doc: Optional[Doc]) -> Dict[int, str]:
    if doc is None:
        return {}
    out = {}
    for lvl, h, text in sections(doc.body):
        m = SECTION_RE.match(h)
        if lvl == 2 and m:
            out[int(m.group(1))] = text.strip()
    return out


def strip_mark(text: str) -> str:
    return MARK_RE.sub("", text).strip()


def compile_spec(uc_arg: str) -> dict:
    from .sync import stamp_doc
    uc = normalize_id(uc_arg)
    with store.locked():
        ws = Workspace()
        if ws.catalog_of(uc) != "use-cases":
            raise BAError(f"{uc} is not a use case")
        ups = upstream(ws, uc)
        rel = ws.doc_rel("use-case-specification", uc)
        old = ws.docs.get(rel)
        prev = _existing_sections(old)
        gen = generated(ws, uc, ups)
        body = [f"# {uc} — {ws.label(uc)}", ""]
        todo = []
        for n, h in enumerate(headings(), 1):
            body += [f"## {n}. {h}", ""]
            if n in gen:
                src, content = gen[n]
                body += [MARK.format(src=src), "", content, ""]
            else:
                text = prev.get(n, "")
                if not text or PLACEHOLDER_RE.search(text):
                    text = PLACEHOLDER.format(hint=NARRATIVE.get(n, "write this section"))
                    todo.append(f"{n}. {h}")
                body += [text, ""]
        fm = dict(old.fm) if old else {"id": uc, "artifact_type": "use-case-specification", "status": "DRAFT",
                                       "version": 1, "baseline": "TO_BE", "origin": "AI"}
        fm.update({"title": ws.label(uc), "relations": relations(ws, uc, ups),
                   "open_questions": _union(ups.values(), "open_questions"),
                   "assumptions": _union(ups.values(), "assumptions"), "updated_at": store.now()})
        p = paths.BA / rel
        store.write_frontmatter(p, fm, "\n".join(body).rstrip() + "\n")
        ws2 = Workspace()
        stamp_doc(ws2, ws2.docs[rel])
    return {"path": paths.show(rel), "narrative_todo": todo}


def check(ws: Workspace, doc: Doc) -> List[str]:
    """Validation messages: placeholders left, or generated sections edited by hand."""
    msgs = []
    have = _existing_sections(doc)
    for n, h in enumerate(headings(), 1):
        if n in NARRATIVE and PLACEHOLDER_RE.search(have.get(n, "")):
            msgs.append(f"section {n}. {h} still has the TODO placeholder — write it")
    if ws.stale_reasons(doc):
        return msgs
    try:
        ups = upstream(ws, doc.id)
    except BAError:
        return msgs
    for n, (src, content) in generated(ws, doc.id, ups).items():
        if " ".join(strip_mark(have.get(n, "")).split()) != " ".join(content.split()):
            msgs.append(f"section {n}. {headings()[n - 1]} differs from its source ({src}) — "
                        f"don't edit generated sections: change the source, then `tools/ba compile {doc.id}`")
    return msgs
